version: '3.8'

volumes:
  influxdb_data: {}

networks:
  monitoring:
    external: true
    name: grafana-hub_default
services:
  influxdb:
    image: influxdb:2.7
    container_name: influxdb
    hostname: influxdb
    volumes:
      - influxdb_data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin  # Your custom username
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin123  # Your custom password (minimum 8 characters)
      - DOCKER_INFLUXDB_INIT_ORG=me  # Your organization name
      - DOCKER_INFLUXDB_INIT_BUCKET=me  # Your default bucket name
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=myadmintoken  # Your custom admin token
      - INFLUXD_HTTP_BIND_ADDRESS=:8086
      - INFLUXD_BOLT_PATH=/var/lib/influxdb2/influxd.bolt
      - INFLUXD_ENGINE_PATH=/var/lib/influxdb2/engine
    ports:
      - "8086:8086"
    networks:
      - monitoring
    restart: unless-stopped
