apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://93.115.144.202:8081

    basicAuth: false
    isDefault: true
    editable: true
  - name: InfluxDB
    type: influxdb
    access: proxy
    orgId: 1
    uid: influxdb
    url: http://influxdb:8086
    basicAuth: false
    isDefault: false
    editable: true
    jsonData:
      version: Flux
      organization: me
      defaultBucket: me
      tlsSkipVerify: true
    secureJsonData:
      token: CA1h5eDHDzN2YHXS3f3tik3Uufa8IUuIGr0IYlZYo3xMfP77RxHFO5MUmhuwLXgmAszqYcAAtk2MedgblBmaWQ==