#  * Copyright 2023 Intel Corporation.
#  *
#  * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
#  * in compliance with the License. You may obtain a copy of the License at
#  *
#  * http://www.apache.org/licenses/LICENSE-2.0
#  *
#  * Unless required by applicable law or agreed to in writing, software distributed under the License
#  * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
#  * or implied. See the License for the specific language governing permissions and limitations under
#  * the License.
#  *
#  * EdgeX Foundry, Napa release
#  *******************************************************************************/
#
#
#
# ************************ This is a generated compose file ****************************
#
# DO NOT MAKE CHANGES that are intended to be permanent to EdgeX edgex-compose repo.
#
# Permanent changes can be made to the source compose files located in the compose-builder folder
# at the top level of the edgex-compose repo.
#
# From the compose-builder folder use `make build` to regenerate all standard compose files variations
#
version: '3'
services:
  app-rules-engine:
    container_name: edgex-app-rules-engine
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
    environment:
      EDGEX_PROFILE: rules-engine
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-app-rules-engine
    hostname: edgex-app-rules-engine
    image: edgexfoundry/app-service-configurable:3.1.1
    networks:
      edgex-network: null
    ports:
    - "127.0.0.1:59701:59701"
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  consul:
    command:
    - agent
    - -ui
    - -bootstrap
    - -server
    - -client
    - 0.0.0.0
    container_name: edgex-core-consul
    hostname: edgex-core-consul
    image: hashicorp/consul:1.16.6
    networks:
      edgex-network: null
    ports:
    - "127.0.0.1:8500:8500"
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: root:root
    volumes:
    - type: volume
      source: consul-config
      target: /consul/config
      volume: {}
    - type: volume
      source: consul-data
      target: /consul/data
      volume: {}
  core-command:
    container_name: edgex-core-command
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      EXTERNALMQTT_URL: tcp://edgex-mqtt-broker:1883
      SERVICE_HOST: edgex-core-command
    hostname: edgex-core-command
    image: edgexfoundry/core-command:3.1.1
    networks:
      edgex-network: null
    ports:
    - "127.0.0.1:59882:59882"
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  core-common-config-bootstrapper:
    container_name: edgex-core-common-config-bootstrapper
    depends_on:
      consul:
        condition: service_started
    environment:
      ALL_SERVICES_DATABASE_HOST: ${DB_HOST}
      #ALL_SERVICES_DATABASE_HOST: edgex-redis-master
      ALL_SERVICES_MESSAGEBUS_HOST: ${DB_HOST}
      ALL_SERVICES_REGISTRY_HOST: edgex-core-consul
      APP_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      DEVICE_SERVICES_CLIENTS_CORE_METADATA_HOST: edgex-core-metadata
      EDGEX_OVERWRITE_CONFIG: "true"
      EDGEX_SECURITY_SECRET_STORE: "false"
    hostname: edgex-core-common-config-bootstrapper
    image: edgexfoundry/core-common-config-bootstrapper:3.1.1
    networks:
      edgex-network: null
    read_only: true
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  core-data:
    container_name: edgex-core-data
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      DATABASE_HOST: ${DB_HOST}
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-data
    hostname: edgex-core-data
    image: edgexfoundry/core-data:3.1.1
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  core-data-2:
    container_name: edgex-core-data-2
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      DATABASE_HOST: ${DB_HOST}
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-data-2
    hostname: edgex-core-data-2
    image: edgexfoundry/core-data:3.1.1
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  core-data-3:
    container_name: edgex-core-data-3
    depends_on:
      consul:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      DATABASE_HOST: ${DB_HOST}
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-data-3
    hostname: edgex-core-data-3
    image: edgexfoundry/core-data:3.1.1
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  core-metadata:
    container_name: edgex-core-metadata
    depends_on:
      consul:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-metadata
    hostname: edgex-core-metadata
    image: edgexfoundry/core-metadata:3.1.1
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  core-metadata-2:
    container_name: edgex-core-metadata-2
    depends_on:
      consul:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-metadata-2
    hostname: edgex-core-metadata-2
    image: edgexfoundry/core-metadata:3.1.1
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  core-metadata-3:
    container_name: edgex-core-metadata-3
    depends_on:
      consul:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-core-metadata-3
    hostname: edgex-core-metadata-3
    image: edgexfoundry/core-metadata:3.1.1
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  device-rest:
    container_name: edgex-device-rest
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-device-rest
    hostname: edgex-device-rest
    image: edgexfoundry/device-rest:3.1.1
    networks:
      edgex-network: null
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  device-virtual:
    container_name: edgex-device-virtual
    depends_on:
      consul:
        condition: service_started
      core-data:
        condition: service_started
      core-metadata:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-device-virtual
    hostname: edgex-device-virtual
    image: edgexfoundry/device-virtual:3.1.1
    networks:
      edgex-network: null
    ports:
    - "127.0.0.1:59900:59900"
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
      #rules-engine:
      #  container_name: edgex-kuiper
      #  environment:
      #    CONNECTION__EDGEX__REDISMSGBUS__PORT: "6379"
      #    CONNECTION__EDGEX__REDISMSGBUS__PROTOCOL: redis
      #    CONNECTION__EDGEX__REDISMSGBUS__SERVER: 192.168.2.105
      #    #CONNECTION__EDGEX__REDISMSGBUS__SERVER: edgex-redis-master
      #    CONNECTION__EDGEX__REDISMSGBUS__TYPE: redis
      #    EDGEX__DEFAULT__PORT: "6379"
      #    EDGEX__DEFAULT__PROTOCOL: redis
      #    #EDGEX__DEFAULT__SERVER: edgex-redis-master
      #    EDGEX__DEFAULT__SERVER: 192.168.2.105
      #    EDGEX__DEFAULT__TOPIC: edgex/rules-events
      #    EDGEX__DEFAULT__TYPE: redis
      #    KUIPER__BASIC__CONSOLELOG: "true"
      #    KUIPER__BASIC__RESTPORT: "59720"
      #  hostname: edgex-kuiper
      #  image: lfedge/ekuiper:1.11.5-alpine
      #  networks:
      #    edgex-network: null
      #  ports:
      #  - "127.0.0.1:59720:59720"
      #  read_only: true
      #  restart: always
      #  security_opt:
      #  - no-new-privileges:true
      #  user: kuiper:kuiper
      #  volumes:
      #  - /etc/localtime:/etc/localtime:ro
      #  - type: volume
      #    source: kuiper-data
      #    target: /kuiper/data
      #    volume: {}
      #  - type: volume
      #    source: kuiper-etc
      #    target: /kuiper/etc
      #    volume: {}
      #  - type: volume
      #    source: kuiper-log
      #    target: /kuiper/log
      #    volume: {}
      #  - type: volume
      #    source: kuiper-plugins
      #    target: /kuiper/plugins
      #    volume: {}
  support-notifications:
    container_name: edgex-support-notifications
    depends_on:
      consul:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-support-notifications
    hostname: edgex-support-notifications
    image: edgexfoundry/support-notifications:3.1.1
    networks:
      edgex-network: null
    ports:
    - "127.0.0.1:59860:59860"
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  support-scheduler:
    container_name: edgex-support-scheduler
    depends_on:
      consul:
        condition: service_started
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      INTERVALACTIONS_SCRUBAGED_HOST: edgex-core-data
      INTERVALACTIONS_SCRUBPUSHED_HOST: edgex-core-data
      SERVICE_HOST: edgex-support-scheduler
    hostname: edgex-support-scheduler
    image: edgexfoundry/support-scheduler:3.1.1
    networks:
      edgex-network: null
    ports:
    - "127.0.0.1:59861:59861"
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  ui:
    container_name: edgex-ui-go
    environment:
      EDGEX_SECURITY_SECRET_STORE: "false"
      SERVICE_HOST: edgex-ui-go
    hostname: edgex-ui-go
    image: edgexfoundry/edgex-ui:3.1.0
    networks:
      edgex-network: null
    ports:
    - "4000:4000"
    read_only: true
    restart: always
    security_opt:
    - no-new-privileges:true
    user: 2002:2001
    volumes:
    - /etc/localtime:/etc/localtime:ro
  nginx:
    image: nginx:alpine
    ports:
    - "8080:80"
    - "59880:59880"
    - "59881:59881"
    - "59986:59986"
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
    - core-data
    - core-data-2
    - core-data-3
    - core-metadata
    - core-metadata-2
    - core-metadata-3
    - core-command
    networks:
      edgex-network: null
    restart: always
networks:
  edgex-network:
    external: true
    name: "edgex-network"
volumes:
  consul-config:
    name: edgex_consul-config
  consul-data:
    name: edgex_consul-data
  kuiper-data:
    name: edgex_kuiper-data
  kuiper-etc:
    name: edgex_kuiper-etc
  kuiper-log:
    name: edgex_kuiper-log
  kuiper-plugins:
    name: edgex_kuiper-plugins
