events {
    worker_connections 1024;
}

http {
    upstream core_data_backend {
        server edgex-core-data:59880;
        server edgex-core-data-2:59880;
        server edgex-core-data-3:59880;
    }

    upstream core_metadata_backend {
        server edgex-core-metadata:59881;
        server edgex-core-metadata-2:59881;
        server edgex-core-metadata-3:59881;
    }

    upstream device_rest_backend {
        server edgex-device-rest:59986;
    }

    server {
        listen 59880;
        location / {
            proxy_pass http://core_data_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 59881;
        location / {
            proxy_pass http://core_metadata_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }

    server {
        listen 59986;
        location / {
            proxy_pass http://device_rest_backend;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
