version: '3.8'

networks:
  tb_network:
    external: true
    name: multiple_tb_network

services:
  # Simple HAProxy Load Balancer with host network
  haproxy-lb:
    image: haproxy:2.8-alpine
    container_name: thingsboard-haproxy-lb
    ports:
      - "8081:8081"
    restart: unless-stopped
    networks:
      tb_network:
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
